services:
  flask_app:
    container_name: flask_app
    image: msystem/flask_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app  # Монтирование текущей директории внутрь контейнера
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - REDIS_HOST=flask_redis
      - REDIS_PORT=6379
    depends_on:
      - flask_db
      - flask_redis
    command: flask run --host=0.0.0.0 --port=4000

  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_redis:
    container_name: flask_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

volumes:
  pgdata: {}
