services:
  flask_app:
    container_name: flask_app
    image: msystem/flask_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - URL=${URL}
    depends_on:
      - flask_db
    command: /bin/sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=4000"

  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
