services:
  flask_app:
    container_name: flask_app
    image: msystem/flask_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app  # Монтирование текущей директории внутрь контейнера
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    command: flask run --host=0.0.0.0 --port=4000
  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
